name: porepy
channels:
  - conda-forge
dependencies:
  - jupyter = 1.0.0
  - vtk
  - gmsh
  - python
  - geos
  - numpy=1.16.3 
  - scipy=1.2.1
  - networkx=2.3
  - sympy=1.4
  - cython=0.29.7
  - numba=0.43.1
  - matplotlib=3.0.3
  - pytest=4.5.0
  - pytest-cov=2.6.1
  - pytest-runner=4.4 
  - pip
  - pip:
    - meshio==2.3.8
    - networkx == 2.3
    - future == 0.17.1
    - six == 1.12.0
    - shapely == 1.6.4.post2
    - shapely[vectorized]==1.6.4.post2
    
